version: 2

# Set the version of Python and other tools you might need
build:
  image: latest

python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
