version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-22.04" # can no longer use build.image but must be build.os

python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
