[tox]
envlist =
    py312
    py312-oldestdeps
    py312-alldeps
    py312-cov
isolated_build = true
requires =
    tox-min-req

[testenv]
usedevelop = True
description = Run tests
deps =
    pytest
commands =
    pytest tests

[testenv:py312-oldestdeps]
usedevelop = True
description = Test with minimum dependency versions
min_req = true
deps =
    pytest
commands =
    pytest tests

[testenv:py312-alldeps]
usedevelop = True
description = Test with latest versions of all dependencies
deps =
    pytest
commands =
    pytest tests

[testenv:py312-cov]
usedevelop = True
description = Test with coverage
deps =
    pytest
    pytest-cov
commands =
    pytest tests --cov=EclipsingBinaries --cov-report=term-missing --cov-fail-under=15

[pytest]
minversion = 7
testpaths =
    tests
filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
source = EclipsingBinaries
omit =
    */EclipsingBinaries/examples/*
    */EclipsingBinaries/docs/*
    */EclipsingBinaries/tests/*
    */EclipsingBinaries/menu.py

[coverage:report]
exclude_lines =
    pragma: no cover
    except ImportError
    raise AssertionError
    raise NotImplementedError
    def main\(.*\):
    pragma: py{ignore_python_version}
