[tox]
envlist =
    py312
    py312-oldestdeps
    py312-alldeps
isolated_build = true


[testenv]
description = Run tests
deps =
    pytest
commands =
    pytest --pyargs EclipsingBinaries

[testenv:py312-oldestdeps]
description = Test with minimum dependency versions
deps =
    pytest
    numpy==1.22.*
    astropy==5.2.*
commands =
    pytest --pyargs EclipsingBinaries

[testenv:py312-alldeps]
description = Test with latest dependencies
deps =
    pytest
commands =
    pytest --pyargs EclipsingBinaries

[testenv:py312-cov]
deps =
    pytest
    pytest-cov
commands =
    pytest --pyargs EclipsingBinaries --cov=EclipsingBinaries --cov-config=setup.cfg

